name: RoME
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - nvidia
  - pytorch
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - https://mirrors.ustc.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-version=12.9=3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h0b41bf4_3
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=12_h832b8c9_netlib
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=12_hd37a5e2_netlib
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.2.13=h4ab18f5_6
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.5.4=h26f9b46_0
  - pip=24.3.1=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.19=hd12c33a_0_cpython
  - python_abi=3.8=8_cp38
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cpu
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sqlite=3.46.0=h6d4b2fc_0
  - tbb=2021.13.0=hb60516a_3
  - tk=8.6.13=noxft_h4845f30_101
  - typing_extensions=4.12.2=pyha770c72_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - certifi==2025.10.5
      - click==8.1.8
      - cmake==4.1.0
      - cycler==0.12.1
      - descartes==1.1.0
      - eval-type-backport==0.2.2
      - fire==0.7.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lit==18.1.8
      - matplotlib==3.5.3
      - mpmath==1.3.0
      - networkx==3.1
      - nuscenes-devkit==1.1.11
      - opencv-python==4.12.0.88
      - pillow==10.4.0
      - platformdirs==4.3.6
      - portalocker==3.0.0
      - pycocotools==2.0.7
      - pymeshlab==2022.2
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pytorch3d==0.7.3
      - scikit-learn==1.3.2
      - scikit-spatial==9.0.1
      - sentry-sdk==2.42.0
      - shapely==1.8.5.post1
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - torch==2.0.0+cu118
      - torchaudio==2.0.0+cu118
      - torchvision==0.15.0+cu118
      - triton==2.0.0
      - urllib3==1.26.20
      - wandb==0.22.2
      - yacs==0.1.8
prefix: /home/stevenchao/miniconda3/envs/RoME
